version: '3.5'

services:
  software-api-enterprise-com:
    image: ${DOCKER_REGISTRY}software-api.enterprise.com:${BRANCH:-develop}.${VERSION:-local}-tests
    container_name: software-api-tests.enterprise.com
    build:
      target: tests
    environment:
      RUN_SONARQUBE: ${RUN_SONARQUBE:-true}
      SONARQUBE_URL: ${SONARQUBE_URL:-http://172.17.0.1:9000}
      SONARQUBE_LOGIN: ${SONARQUBE_LOGIN}
      SONARQUBE_PROJECT: software-api.enterprise.com
      SONARQUBE_PROJECT_VERSION: ${VERSION:-local}
    volumes:
      - test-result:/TestResults

volumes:
  test-result:
    name: ${DOCKERCOMPOSE_CI_VOLUME_NAME:-app-test-results}

networks:
  default:
    name: ns-software-api-${BRANCH}-${VERSION}-tests    
