version: '3.5'

services:
  software-api-enterprise-com:
    image: ${DOCKER_REGISTRY}software-api.enterprise.com:${BRANCH:-develop}.${VERSION:-local}
    container_name: software-api-local.enterprise.com
    build:
      target: deploy
      context: .
      dockerfile: Software/Dockerfile
