version: '3.5'

services:
  software-api-enterprise-com:
    image: ${DOCKER_REGISTRY}software-api.enterprise.com:${BRANCH:-develop}.${VERSION:-local}-build
    build:
      target: build
    volumes:
      - app:/var/release/

volumes:
  app:
    name: ${DOCKERCOMPOSE_PUBLISH_VOLUME_NAME:-dotnetcoreseed.tjmt.jus.br-extract-app}