version: '3.5'

services:
  software-api-enterprise-com:
    image: ${DOCKER_REGISTRY}software-api.enterprise.com:${BRANCH}.${VERSION}
    ports:
      - "5432:5432"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.20'
          memory: 3072M
        reservations:
          cpus: '0.01'
          memory: 1M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 120s
    labels:
      kompose.service.expose: software-api-rc.enterprise.com

networks:
  default:
    name: ns-software-rc
